[package]
name = "i2c"
version = "0.1.1"
authors = ["gitllama"]
description = "IR Remote Controller"
edition = "2018"

[dependencies]
clap = {version = "2.33.3", features = ["yaml"]}
rppal = "*"
byteorder = "*"
# serde_json = "*"
yaml-rust = "*"